version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.22

    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
          - v1-dependencies-
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

  test: 
    docker:
      - image: circleci/node:12.22
    steps: 
      - checkout
      - run:
          name: Run tests with coverage
          command: npm test --coverage
  
  deploy: 
    docker:
      - image: circleci/node:12.22
    - run:
        name: Deploy application
        command: sls deploy --stage pre

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test